### ISSUE TITLE
Orient Documentation toward Simpler Example

### ISSUE THREAD

**Issue by matttproud** [miekg/gitopper#36]
The [README](https://github.com/miekg/gitopper/blob/main/README.md) for the project orients itself around a hypothetical Grafana setup.  For the purposes of easy setup, demonstration, and even testing, I would like to propose amending the README toward a different example, something that can be installed from the base package repository for a given Linux distribution (e.g., Debian).  [Grafana's setup on Debian](https://grafana.com/docs/grafana/latest/setup-grafana/installation/debian/) requires adding a separate repository and keychain entry, which is a little annoying.  I am at a loss of an immediate suggestion and want to see what you think, @miekg.

**Comment by miekg** [comment]
Do Prometheus? With a prometheus.yml?

**Comment by matttproud** [comment]
Why not?  It's the tenth birthday:
https://promlabs.com/blog/2022/11/24/prometheus-turns-10!

**Comment by miekg** [comment]
DNS is another :-) 

(we could in the prom case also have a file_sd_config that gets generated and updated with a github workflow in some upstream repo (blah-origin) and then commited *back into* repo, so it get distributed)

**Comment by miekg** [comment]
closed by #39 
(need to check the apt-get install as well, but now stumped with a different problem)
